export interface Property {
    "@odata.context": string
    value: Value[]
    "@odata.nextLink": string
  }
  
  export interface Value {
    "@odata.id": string
    AdditionalParcelsYN: boolean
    Appliances: string[]
    AssociationAmenities?: string[]
    AssociationFee?: number
    AssociationFeeFrequency?: string
    AssociationFeeIncludes?: string[]
    AssociationYN: boolean
    AttachedGarageYN?: boolean
    BathroomsFull: number
    BathroomsHalf: number
    BathroomsTotalInteger: number
    BedroomsTotal: number
    BuildingAreaSource: string
    BuildingAreaTotal?: number
    BuildingAreaUnits?: string
    MFR_CalculatedListPriceByCalculatedSqFt: string
    MFR_CDDYN: string
    City: string
    CloseDate: string
    ClosePrice: number
    MFR_ClosePriceByCalculatedListPriceRatio: string
    MFR_ClosePriceByCalculatedSqFt: string
    CommunityFeatures?: string[]
    ConstructionMaterials: string[]
    MFR_ContractStatus: string
    Cooling: string[]
    CountyOrParish: string
    CumulativeDaysOnMarket: number
    MFR_CurrentPrice: string
    DaysOnMarket: number
    MFR_DaysToClosed: string
    DirectionFaces?: string
    MFR_DPRURL: string
    MFR_DPRURL2: string
    MFR_DPRYN: string
    MFR_ExpectedClosingDate: string
    ExteriorFeatures?: string[]
    FireplaceYN: boolean
    Flooring: string[]
    MFR_FloorNumber?: string
    FoundationDetails: string[]
    MFR_FutureLandUse?: string
    GarageSpaces?: number
    GarageYN?: boolean
    Heating: string[]
    MFR_HomesteadYN: string
    HomeWarrantyYN: boolean
    InteriorFeatures?: string[]
    InternetAddressDisplayYN: boolean
    InternetAutomatedValuationDisplayYN: boolean
    InternetConsumerCommentYN?: boolean
    InternetEntireListingDisplayYN: boolean
    Levels?: string[]
    ListAgentAOR: string
    ListAgentDirectPhone: string
    ListAgentEmail: string
    ListAgentFax: string
    ListAgentFullName: string
    ListAgentKey: string
    ListAgentMlsId: string
    ListAgentOfficePhoneExt?: string
    ListAgentPager?: string
    ListAgentURL?: string
    ListAOR: string
    ListingAgreement: string
    ListingContractDate: string
    ListingId: string
    ListingKey: string
    OriginatingSystemKey: string
    ListingTerms?: string[]
    ListOfficeFax?: string
    MFR_ListOfficeHeadOfficeKeyNumeric: string
    ListOfficeKey: string
    ListOfficeMlsId: string
    ListOfficeName: string
    ListOfficePhone: string
    ListPrice: number
    LivingArea: number
    LivingAreaSource: string
    LivingAreaUnits: string
    LotFeatures?: string[]
    LotSizeAcres: number
    LotSizeSquareFeet: number
    MFR_MaxPetWeight?: string
    MFR_MillageRate?: string
    MLSAreaMajor: string
    MlsStatus: string
    NewConstructionYN: boolean
    MFR_NumberOfPets?: string
    OffMarketDate: string
    OriginalEntryTimestamp: string
    OriginalListPrice: number
    MFR_OriginatingSystemName_: string
    MFR_OriginatingSystemTimestamp: string
    Ownership: string
    ParcelNumber: string
    ParkingFeatures?: string[]
    PatioAndPorchFeatures?: string[]
    MFR_PetRestrictions?: string
    PetsAllowed?: string[]
    MFR_PetSize?: string
    PhotosChangeTimestamp: string
    PhotosCount: number
    PoolFeatures?: string[]
    PoolPrivateYN: boolean
    PostalCode: string
    PostalCodePlus4?: string
    PreviousListPrice?: number
    MFR_PreviousStatus?: string
    PriceChangeTimestamp?: string
    PrivateRemarks?: string
    MFR_PropertyDescription?: string
    PropertySubType: string
    PropertyType: string
    PublicRemarks: string
    PublicSurveyRange?: string
    PublicSurveySection?: string
    PurchaseContractDate: string
    MFR_RATIO_ClosePrice_By_ListPrice: string
    MFR_RATIO_ClosePrice_By_OriginalListPrice: string
    MFR_RATIO_CurrentPrice_By_CalculatedSqFt: string
    Roof: string[]
    MFR_RoomCount: string
    SecurityFeatures?: string[]
    ShowingRequirements: string[]
    SpaYN?: boolean
    SpecialListingConditions: string[]
    StandardStatus: string
    StateOrProvince: string
    StatusChangeTimestamp: string
    StoriesTotal?: number
    SubdivisionName: string
    TaxAnnualAmount: number
    TaxBookNumber?: string
    TaxLegalDescription: string
    TaxLot?: string
    TaxYear: number
    MFR_TotalAcreage: string
    Township?: string
    Utilities?: string[]
    VirtualTourURLUnbranded?: string
    MFR_WaterAccessYN?: string
    MFR_WaterExtrasYN: string
    WaterfrontYN: boolean
    MFR_WaterViewYN?: string
    WindowFeatures?: string[]
    YearBuilt: number
    MFR_PublicRemarksAgent: string
    MFR_SDEOYN: string
    MFR_TotalAnnualFees?: string
    MFR_TotalMonthlyFees?: string
    OriginatingSystemName: string
    ModificationTimestamp: string
    Media: Medum[]
    BuyerAgentAOR: string
    BuyerAgentFullName: string
    BuyerAgentKey: string
    BuyerAgentMlsId: string
    BuyerOfficeKey: string
    BuyerOfficeMlsId: string
    BuyerOfficeName: string
    Directions: string
    Latitude: number
    Longitude: number
    MFR_AssociationFeeRequirement: string
    MFR_BuildingNameNumber?: string
    MFR_SWSubdivCommunityName: string
    MFR_SubdivisionNum: string
    StreetName: string
    StreetNumber: string
    StreetSuffix?: string
    UnitNumber?: string
    UnparsedAddress: string
    MlgCanView: boolean
    MlgCanUse: string[]
    MFR_AdditionalRooms?: string
    ArchitecturalStyle?: string[]
    AssociationName?: string
    MFR_AvailableForLeaseYN?: string
    MFR_BackupsRequestedYN?: string
    MFR_BuildingElevatorYN?: string
    MFR_CondoFees?: string
    MFR_CondoFeesTerm?: string
    ElementarySchool?: string
    MFR_ExpectedLeaseDate?: string
    MFR_FloodZoneCode?: string
    HighSchool?: string
    MiddleOrJuniorSchool?: string
    MFR_MinimumLease?: string
    MFR_NumTimesperYear?: string
    OtherStructures?: string[]
    MFR_PlannedUnitDevelopmentYN?: string
    Sewer?: string[]
    Vegetation?: string[]
    View?: string[]
    WaterBodyName?: string
    WaterSource?: string[]
    MFR_WaterView?: string
    Zoning?: string
    MFR_ZoningCompatibleYN?: string
    StreetDirPrefix?: string
    MFR_OtherExemptionsYN?: string
    BodyType?: string[]
    CarportSpaces?: number
    CarportYN?: boolean
    MFR_ExistLseTenantYN?: string
    Furnished?: string
    LaundryFeatures?: string[]
    MFR_RealtorInfo?: string
    SeniorCommunityYN?: boolean
    MFR_SoldRemarks?: string
    MFR_BuildingAreaTotalSrchSqM?: string
    MFR_LivingAreaMeters?: string
    OccupantType?: string
    MFR_AttributionContact?: string
    MFR_ListOfficeContactPreferred?: string
    UniversalPropertyId?: string
    MFR_MonthlyHOAAmount?: string
    PropertyCondition?: string[]
    TaxBlock?: string
    LotSizeDimensions?: string
    Model?: string
    MFR_ComplexCommunityNameNCCB?: string
    MFR_SWSubdivCondoNum?: string
    MFR_DisasterMitigation?: string
    GreenEnergyEfficient?: string[]
    GreenIndoorAirQuality?: string[]
    MFR_GreenLandscaping?: string
    GreenWaterConservation?: string[]
    TaxOtherAnnualAssessmentAmount?: number
    MFR_MontlyMaintAmtAdditionToHOA?: string
    MFR_OtherFeesAmount?: string
    MFR_OtherFeesTerm?: string
    MFR_ProjectedCompletionDate?: string
    VirtualTourURLBranded?: string
    MFR_VirtualTourURLBranded2?: string
    CoBuyerAgentFullName?: string
    CoBuyerAgentKey?: string
    CoBuyerAgentMlsId?: string
    CoBuyerOfficeKey?: string
    CoBuyerOfficeMlsId?: string
    CoBuyerOfficeName?: string
    MFR_GarageDimensions?: string
    CoListAgentDirectPhone?: string
    CoListAgentFullName?: string
    CoListAgentKey?: string
    CoListAgentMlsId?: string
    CoListOfficeKey?: string
    CoListOfficeMlsId?: string
    CoListOfficeName?: string
    MFR_MonthlyCondoFeeAmount?: string
    MFR_WaterAccess?: string
    WaterfrontFeatures?: string[]
    MFR_LeaseRestrictionsYN?: string
    StreetDirSuffix?: string
    MFR_WaterfrontFeetTotal?: string
    FireplaceFeatures?: string[]
  }
  
  export interface Medum {
    Order: number
    LongDescription: string
    MediaType: string
    ImageWidth: number
    ImageHeight: number
    ImageSizeDescription: string
    MediaURL: string
    MediaModificationTimestamp: string
    MediaKey: string
    Permission: string[]
  }
  