export interface Property {
  value: Value[]
  "@odata.nextLink": string
  "@odata.context": string
  "@odata.count": number
}

export interface Value {
  StreetDirPrefix: any
  DistanceToStreetComments: any
  PublicSurveyRange: any
  LeaseAssignableYN: any
  GreenWaterConservation: any[]
  NumberOfUnitsMoMo: any
  LivingAreaUnits: string
  CoListAgentCellPhone: any
  SeatingCapacity: any
  TaxLegalDescription: string
  LockBoxLocation: string
  BuyerAgentDesignation: any[]
  YearEstablished: any
  BuyerTeamKey: any
  ListPriceLow: any
  ContingentDate: string
  LaundryFeatures: string[]
  Flooring: string[]
  PhotosCount: number
  FireplacesTotal: number
  ListTeamKey: any
  AdditionalParcelsYN: boolean
  CoBuyerAgentDirectPhone: any
  WaterfrontFeatures: any[]
  PastureArea: any
  SubAgencyCompensation: any
  ViewYN: boolean
  SeniorCommunityYN: boolean
  Cooling: string[]
  ExteriorFeatures: string[]
  CountryRegion: any
  OtherParking: any
  IrrigationWaterRightsAcres: any
  SourceSystemID: any
  StatusChangeTimestamp: string
  SecurityFeatures: any[]
  BuyerAgentFullName: any
  RVParkingDimensions: any
  CoBuyerAgentDesignation: any[]
  CoBuyerAgentNamePrefix: any
  CoBuyerAgentLastName: any
  PrivateOfficeRemarks: string
  DocumentsCount: number
  CancelationDate: any
  AssociationName: string
  DistanceToBusComments: any
  TaxExemptions: any[]
  CoListAgentURL: any
  BuildingName: string
  YearsCurrentOwner: any
  DistanceToSchoolsComments: any
  ListAgentPreferredPhoneExt: any
  AssociationFeeFrequency: string
  CrossStreet: any
  OccupantPhone: string
  HeatingYN: boolean
  CoBuyerAgentStateLicense: any
  WaterBodyName: any
  ManagerExpense: any
  DistanceToSewerNumeric: any
  DistanceToGasComments: any
  CoBuyerAgentMiddleName: any
  AboveGradeFinishedArea: number
  BuyerAgentFax: any
  MajorChangeType: string
  ListingKeyNumeric: any
  Appliances: string[]
  MLSAreaMajor: any
  TaxAnnualAmount: number
  LandLeaseAmount: any
  CoBuyerAgentPreferredPhoneExt: any
  CoListAgentPreferredPhone: any
  CurrentUse: any[]
  OriginatingSystemKey: string
  CountyOrParish: string
  PropertyType: string
  BathroomsTotalDecimal: number
  NumberOfPads: any
  TaxParcelLetter: any
  OriginatingSystemName: any
  AssociationYN: boolean
  MlsStatus: string
  CarrierRoute: any
  BuyerOfficeURL: any
  StreetNumber: string
  GrossScheduledIncome: any
  LeaseTerm: any
  ListingKey: string
  CoBuyerAgentNameSuffix: any
  CoListAgentNamePrefix: any
  AssociationPhone2: any
  CommonWalls: string[]
  ListAgentVoiceMail: any
  CommonInterest: any
  ListAgentKeyNumeric: any
  CoListAgentLastName: any
  ShowingContactType: string[]
  CoBuyerAgentMobilePhone: any
  Vegetation: any[]
  IrrigationWaterRightsYN: any
  BuyerAgentMiddleName: any
  ElementarySchool: string
  DistanceToFreewayComments: any
  StreetDirSuffix: any
  DistanceToSchoolsNumeric: any
  CoBuyerOfficePhone: any
  CoListOfficePhoneExt: any
  ListAgentFirstName: string
  DistanceToShoppingNumeric: any
  TaxMapNumber: any
  Directions: string
  Concessions: any
  AttachedGarageYN: boolean
  OnMarketTimestamp: any
  DistanceToBusNumeric: any
  StandardStatus: string
  CultivatedArea: any
  Roof: string[]
  BuyerAgentNamePrefix: any
  ParkingTotal: number
  ContinentRegion: any
  ListAgentOfficePhone: any
  ListAgentHomePhone: any
  BuyerTeamName: any
  CoListOfficeKeyNumeric: any
  DistanceToElectricUnits: any
  PoolPrivateYN: boolean
  PropertyUniversalID: any
  AdditionalParcelsDescription: any
  Township: any
  ListingTerms: any[]
  NumberOfUnitsLeased: any
  FurnitureReplacementExpense: any
  DistanceToStreetUnits: any
  BuyerAgentNameSuffix: any
  GardenerExpense: any
  DistanceToSchoolBusUnits: any
  BuilderName: string
  BuyerAgentStateLicense: any
  ListOfficeEmail: any
  PropertySubType: string
  CoListAgentFirstName: any
  BuyerAgentDirectPhone: any
  CoBuyerAgentPreferredPhone: any
  OtherExpense: any
  Possession: string[]
  CoListAgentOfficePhone: any
  WaterfrontYN: boolean
  BathroomsFull: number
  LotSizeAcres: number
  SubdivisionName: string
  SpecialLicenses: any[]
  BuyerOfficeAOR: any
  InternetAddressDisplayYN: boolean
  Fencing: string[]
  LotSizeSource: string
  WithdrawnDate: any
  DistanceToWaterNumeric: any
  VideosCount: any
  Contingency: string
  FarmCreditServiceInclYN: any
  ListingService: string
  Elevation: number
  WaterSource: string[]
  Topography: any
  SubAgencyCompensationType: any
  ProfessionalManagementExpense: any
  DistanceToFreewayUnits: any
  DoorFeatures: string[]
  StoriesTotal: number
  YearBuilt: number
  ElectricOnPropertyYN: boolean
  MapCoordinateSource: any
  StateRegion: any
  IrrigationSource: any[]
  BathroomsPartial: number
  CoListOfficeFax: any
  Disclaimer: string
  ZoningDescription: string
  PreviousListPrice: number
  LandLeaseYN: boolean
  VacancyAllowanceRate: any
  NumberOfSeparateWaterMeters: any
  DaysOnMarket: number
  PetsAllowed: any[]
  CoBuyerAgentVoiceMailExt: any
  BuyerAgencyCompensationType: any
  ListAgentFax: any
  NetOperatingIncome: any
  SerialXX: any
  OccupantType: string
  OtherStructures: any[]
  AssociationAmenities: string[]
  BodyType: any[]
  ClosePrice: any
  VirtualTourURLZillow: any
  ListAgentDesignation: any[]
  BuyerAgentPreferredPhone: any
  DistanceToPhoneServiceComments: any
  PoolExpense: any
  PendingTimestamp: string
  CoBuyerAgentURL: any
  StreetNumberNumeric: any
  ListAgentCellPhone: any
  CoListAgentOfficePhoneExt: any
  IncomeIncludes: any[]
  CoBuyerAgentVoiceMail: any
  LivingArea: number
  TaxAssessedValue: number
  BuyerTeamKeyNumeric: any
  CoListAgentKeyNumeric: any
  CumulativeDaysOnMarket: any
  CoListAgentStateLicense: any
  ParkingFeatures: any[]
  PostalCodePlus4: any
  ListAgentPreferredPhone: string
  CoBuyerAgentHomePhone: any
  BuyerOfficePhoneExt: any
  PoolFeatures: any[]
  BuyerAgentOfficePhoneExt: any
  NumberOfUnitsInCommunity: any
  Heating: string[]
  StructureType: any[]
  BuildingAreaSource: string
  BathroomsOneQuarter: number
  BuilderModel: string
  CoBuyerAgentTollFreePhone: any
  TotalActualRent: any
  TrashExpense: any
  CoListAgentMlsId: any
  DistanceToStreetNumeric: any
  PublicSurveyTownship: any
  ListAgentMiddleName: string
  OwnerPays: any[]
  BedroomsPossible: number
  BuyerAgentVoiceMailExt: any
  BuyerOfficePhone: any
  RoadResponsibility: any[]
  ListingAgreement: any
  PublicSurveySection: any
  CoListOfficeEmail: any
  AssociationName2: string
  ListingId: string
  DocumentsChangeTimestamp: any
  CommunityFeatures: string[]
  ShowingStartTime: any
  BathroomsTotalInteger: number
  ParkManagerName: any
  MapCoordinate: any
  RoomsTotal: number
  DistanceToPlaceofWorshipComments: any
  ListAgentOfficePhoneExt: any
  BuildingAreaUnits: string
  City: string
  OwnerPhone: any
  InternetEntireListingDisplayYN: boolean
  CropsIncludedYN: any
  BuyerAgentOfficePhone: any
  GrazingPermitsBlmYN: any
  BuyerAgencyCompensation: any
  CoBuyerOfficeKeyNumeric: any
  LeaseExpiration: any
  ListAgentNameSuffix: any
  ShowingAdvanceNotice: any
  SerialX: any
  InternetAutomatedValuationDisplayYN: boolean
  BuyerAgentTollFreePhone: any
  SerialU: any
  TaxYear: number
  Telephone: string[]
  DirectionFaces: string
  SourceSystemName: any
  PossibleUse: any[]
  Furnished: any
  DistanceToSchoolBusComments: any
  ConstructionMaterials: string[]
  SuppliesExpense: any
  ListOfficeURL: any
  RangeArea: any
  ListingInputOriginalMedia: any
  OccupantName: string
  BuyerOfficeKey: any
  ShowingEndTime: any
  TaxOtherAnnualAssessmentAmount: any
  PrivateRemarks: string
  InternetConsumerCommentYN: boolean
  BuildingAreaTotal: number
  YearBuiltSource: string
  OtherEquipment: string[]
  HabitableResidenceYN: any
  PestControlExpense: any
  LaborInformation: any[]
  LandLeaseAmountFrequency: any
  BedroomsTotal: number
  ShowingInstructions: string
  CoBuyerOfficeEmail: any
  CoListAgentDesignation: any[]
  CoListAgentDirectPhone: any
  CoolingYN: boolean
  GreenSustainability: any[]
  InsuranceExpense: any
  ListAgentKey: string
  OnMarketDate: string
  CarportSpaces: number
  LotSizeUnits: any
  ListAgentEmail: any
  ContractStatusChangeDate: string
  BuyerAgentHomePhone: any
  LeaseAmountFrequency: any
  MajorChangeTimestamp: any
  ElevationUnits: string
  CoBuyerAgentEmail: any
  WalkScore: any
  GarageYN: boolean
  HoursDaysOfOperation: any[]
  BuyerAgentPreferredPhoneExt: any
  DistanceToWaterUnits: any
  Make: any
  Longitude: number
  AvailabilityDate: string
  TaxTract: string
  Skirt: any[]
  BuyerAgentURL: any
  BuyerOfficeFax: any
  CarportYN: boolean
  PublicRemarks: string
  FinancialDataSource: any[]
  CoBuyerAgentKey: any
  PostalCity: any
  CurrentFinancing: string[]
  CableTvExpense: any
  NumberOfSeparateElectricMeters: any
  ElementarySchoolDistrict: string
  NumberOfFullTimeEmployees: any
  OffMarketTimestamp: any
  CoBuyerOfficeFax: any
  CoBuyerAgentFirstName: any
  CoBuyerAgentPager: any
  CoListOfficeName: any
  PurchaseContractDate: any
  ListAgentVoiceMailExt: any
  RoadSurfaceType: string[]
  ListAgentPager: any
  PriceChangeTimestamp: string
  MapURL: any
  CoListAgentPager: any
  LeasableArea: any
  ListingContractDate: string
  CoListOfficeKey: any
  MLSAreaMinor: any
  FarmLandAreaUnits: any
  Zoning: string
  ListAgentAOR: any
  CoBuyerAgentKeyNumeric: any
  GreenIndoorAirQuality: any[]
  LivingAreaSource: string
  MaintenanceExpense: any
  BuyerAgentVoiceMail: any
  DistanceToElectricNumeric: any
  ListAOR: any
  BelowGradeFinishedArea: number
  CoBuyerOfficeName: any
  ListOfficeName: string
  TaxBlock: string
  CoListAgentTollFreePhone: any
  BuyerFinancing: string[]
  GreenLocation: any[]
  MobileWidth: any
  GrazingPermitsPrivateYN: any
  Basement: string[]
  BusinessType: string[]
  DualVariableCompensationYN: boolean
  Latitude: number
  NumberOfSeparateGasMeters: any
  PhotosChangeTimestamp: any
  ListPrice: number
  RoadFrontageType: any[]
  BuyerAgentKeyNumeric: any
  ListAgentTollFreePhone: any
  DistanceToGasUnits: any
  DistanceToPlaceofWorshipNumeric: any
  ListOfficePhone: any
  CoListAgentFax: any
  GreenEnergyGeneration: any[]
  DOH1: any
  DOH2: any
  FoundationArea: number
  DOH3: any
  BelowGradeFinishedAreaSource: string
  CoBuyerOfficeKey: any
  CoListAgentHomePhone: any
  ElectricExpense: any
  CoListOfficeMlsId: any
  DistanceToElectricComments: any
  CoBuyerOfficePhoneExt: any
  AssociationFee2Frequency: string
  CoListAgentVoiceMailExt: any
  StateOrProvince: string
  AboveGradeFinishedAreaUnits: string
  DistanceToSewerComments: any
  ListOfficeAOR: any
  StreetAdditionalInfo: any
  GreenBuildingVerificationType: any
  CoveredSpaces: number
  MiddleOrJuniorSchool: string
  AssociationFeeIncludes: string[]
  CoListAgentMobilePhone: any
  ConcessionsComments: any
  SyndicateTo: string[]
  VirtualTourURLUnbranded: any
  Gas: string[]
  CoListAgentEmail: any
  LandLeaseExpirationDate: any
  FrontageLength: string
  WorkmansCompensationExpense: any
  ListOfficeKeyNumeric: any
  CoListOfficeAOR: any
  Disclosures: any[]
  ListOfficeKey: string
  DistanceToGasNumeric: any
  FireplaceYN: boolean
  BathroomsThreeQuarter: number
  CoBuyerAgentCellPhone: any
  BridgeModificationTimestamp: string
  YearBuiltEffective: any
  EntryLevel: any
  ListAgentFullName: string
  TaxBookNumber: any
  DistanceToSchoolBusNumeric: any
  ListAgentMobilePhone: any
  ShowingContactPhoneExt: any
  MainLevelBathrooms: number
  PropertyCondition: any[]
  FrontageType: string[]
  Stories: number
  DevelopmentStatus: any[]
  GrossIncome: any
  ParcelNumber: string
  ShowingDays: any
  CoBuyerAgentAOR: any
  ShowingRequirements: any
  UnitsFurnished: any
  FuelExpense: any
  CoListAgentVoiceMail: any
  FoundationDetails: string[]
  View: string[]
  SignOnPropertyYN: boolean
  OperatingExpense: any
  LeaseRenewalOptionYN: any
  LeaseRenewalCompensation: any[]
  YearBuiltDetails: string
  BuyerAgentPager: any
  HighSchool: string
  LeaseConsideredYN: boolean
  HomeWarrantyYN: boolean
  Levels: string[]
  OperatingExpenseIncludes: any[]
  StreetSuffixModifier: any
  IDXParticipationYN: boolean
  DistanceToFreewayNumeric: any
  ListAgentLastName: string
  ListAgentURL: any
  InteriorFeatures: string[]
  LockBoxType: string[]
  OffMarketDate: any
  CoBuyerAgentMlsId: any
  PowerProductionType: any
  DistanceToPhoneServiceNumeric: any
  DistanceToWaterComments: any
  CloseDate: any
  ApprovalStatus: any
  StreetSuffix: any
  DistanceToPhoneServiceUnits: any
  HorseAmenities: any[]
  ListAgentMlsId: string
  CoListAgentNameSuffix: any
  ListOfficePhoneExt: any
  WaterSewerExpense: any
  GrazingPermitsForestServiceYN: any
  LotSizeDimensions: string
  ModificationTimestamp: string
  PropertyAttachedYN: boolean
  BuyerAgentKey: any
  TaxLot: string
  BusinessName: string
  BuyerAgentEmail: any
  Coordinates: number[]
  AccessCode: string
  CoBuyerOfficeMlsId: any
  ListAgentNamePrefix: any
  OriginatingSystemID: string
  HorseYN: boolean
  LotDimensionsSource: string
  Country: string
  UnitNumber: string
  CoListAgentPreferredPhoneExt: any
  OpenParkingYN: boolean
  TransactionBrokerCompensation: any
  LeasableAreaUnits: any
  MobileLength: any
  CoBuyerOfficeAOR: any
  NumberOfUnitsVacant: any
  ListOfficeMlsId: string
  Inclusions: string
  ListTeamKeyNumeric: any
  ListAgentDirectPhone: any
  CoBuyerAgentOfficePhone: any
  VacancyAllowance: any
  AssociationPhone: string
  ConcessionsAmount: any
  VirtualTourURLBranded: any
  RoomType: any
  CoListAgentFullName: any
  CoListAgentKey: any
  BelowGradeFinishedAreaUnits: string
  CoListAgentMiddleName: any
  CoListOfficeURL: any
  RentControlYN: any
  EntryLocation: string
  BuyerAgentMobilePhone: any
  SpaYN: boolean
  SpaFeatures: any[]
  ShowingContactPhone: string
  BuyerAgentFirstName: any
  DistanceToPlaceofWorshipUnits: any
  ExistingLeaseType: any[]
  BathroomsHalf: number
  GardnerExpense: any
  LotSizeArea: any
  Sewer: string[]
  ExpirationDate: any
  SyndicationRemarks: any
  Model: any
  BuyerAgentLastName: any
  MaloneId: any
  ListAgentStateLicense: any
  StreetName: string
  ShowingAttendedYN: any
  AboveGradeFinishedAreaSource: string
  ListOfficeFax: any
  AnchorsCoTenants: string
  PatioAndPorchFeatures: any[]
  BuyerAgentCellPhone: any
  NumberOfLots: any
  ParkManagerPhone: any
  ListTeamName: any
  MainLevelBedrooms: any
  CityRegion: string
  NumberOfPartTimeEmployees: any
  LockBoxSerialNumber: string
  DistanceToBusUnits: any
  Utilities: any[]
  FireplaceFeatures: string[]
  WindowFeatures: any[]
  SpecialListingConditions: string[]
  NewConstructionYN: boolean
  BuyerAgentAOR: any
  ParkName: any
  NumberOfBuildings: any
  GarageSpaces: number
  OriginalListPrice: number
  AssociationFee2: number
  HoursDaysOfOperationDescription: any
  GreenEnergyEfficient: string[]
  Media: Medum[]
  CapRate: any
  RentIncludes: any[]
  DistanceToSchoolsUnits: any
  BuyerOfficeKeyNumeric: any
  UnitTypeType: any
  AccessibilityFeatures: any[]
  FarmLandAreaSource: any
  HighSchoolDistrict: string
  OriginalEntryTimestamp: string
  BuildingFeatures: string[]
  OwnershipType: any
  SourceSystemKey: any
  Ownership: string
  BuyerAgentMlsId: any
  OwnerName: any
  Exclusions: string
  CopyrightNotice: string
  ShowingContactName: string
  MobileDimUnits: any
  LotFeatures: any[]
  CoBuyerAgentOfficePhoneExt: any
  License3: any
  PostalCode: string
  License1: any
  License2: any
  BuyerOfficeMlsId: any
  DocumentsAvailable: any[]
  DistanceToShoppingUnits: any
  NumberOfUnitsTotal: number
  BuyerOfficeName: any
  AssociationFee: number
  LeaseAmount: any
  LotSizeSquareFeet: number
  DistanceToSewerUnits: any
  CoBuyerAgentFullName: any
  TenantPays: any[]
  MiddleOrJuniorSchoolDistrict: string
  DistanceToShoppingComments: any
  Electric: any[]
  ArchitecturalStyle: string[]
  MobileHomeRemainsYN: any
  NewTaxesExpense: any
  VideosChangeTimestamp: any
  CoBuyerOfficeURL: any
  TaxStatusCurrent: string[]
  UnparsedAddress: string
  OpenParkingSpaces: any
  CoListOfficePhone: any
  TransactionBrokerCompensationType: any
  WoodedArea: any
  LicensesExpense: any
  BuyerOfficeEmail: any
  CoListAgentAOR: any
  CoBuyerAgentFax: any
  FeedTypes: any[]
  "@odata.id": string
}

export interface Medum {
  Order: number
  MediaURL: string
  ResourceRecordKey: string
  ResourceName: string
  ClassName: string
  MediaCategory: string
  MimeType: string
  MediaObjectID: string
  ShortDescription: string
}
